momento/views.py
from flask import Blueprint, redirect, render_template, request, Flask, session, url_for, flash, send_file
import io, time
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required, current_user
from . import db
from .models import *
from sqlalchemy import desc, asc, and_
from werkzeug.utils import secure_filename

views = Blueprint('views', __name__)

@views.route('/')
def index_page(): 
     return render_template('index.html')

@views.route('/homepage')
@login_required
def homepage():
     current_user_id = current_user.id
     user_comrades = Comrades.query.filter_by(owner_id = current_user_id).all()

     comrades = [comrade for comrade in user_comrades]
     comrades_id = [comrade.comrade_id for comrade in user_comrades]

    

     comrades_id = comrades_id + [current_user_id]


     posts = Posts.query.filter(Posts.user_id.in_(comrades_id)).order_by(desc(Posts.id)).all()
     liked_posts = [like.post_id for like in UserLikedPosts.query.filter_by(user_id = current_user_id).all()]

     
     notifications = Notifications.query.filter_by(target_id = current_user_id).order_by(desc(Notifications.id)).all()     
     notificationCount = Notifications.query.filter_by(owner_id = current_user_id).first()

     try:
          notificationCount = notificationCount.unread_notification_count
     except:
          print('new account created')

     activeUsers =  ActiveUsers.query.all()
         
     searchHistory = SearchHistory.query.filter_by(owner_id = current_user_id).order_by(desc(SearchHistory.id)).all()

     allUsers = User.query.filter(User.id != current_user_id).all()
     currentUser = User.query.filter_by(id = current_user_id).first()

     ALLUSERS = User.query.filter(User.highscore != 0).order_by(desc(User.highscore)).all()

  
     firstName = current_user.firstName
     lastName = current_user.lastName
     name = firstName + ' ' + lastName

          
     return render_template('homepage.html',
                              ALLUSERS = ALLUSERS,
                              users = allUsers,
                              currentUser = currentUser,
                              comrades = comrades,
                              name = name,
                              posts = posts,
                              time = time,
                              liked_posts = liked_posts,
                              notifications = notifications,
                              notificationCount = notificationCount,
                              activeUsers = activeUsers,
                              searchHistory = searchHistory
                      
                              )

@views.route('/userprofile', methods = ['POST','GET'])
@login_required
def user_profile_page():
     current_user_id = current_user.id
     liked_posts = [like.post_id for like in UserLikedPosts.query.filter_by(user_id = current_user_id).all()]
     searchHistory = SearchHistory.query.filter_by(owner_id = current_user_id).order_by(desc(SearchHistory.id)).all()

     posts = Posts.query.filter_by(user_id = current_user_id).order_by(desc(Posts.id)).all()
     
     notifications = Notifications.query.filter_by(target_id = current_user_id).order_by(desc(Notifications.id)).all()     
     notificationCount = Notifications.query.filter_by(owner_id = current_user_id).first()
     notificationCount = notificationCount.unread_notification_count
     

     bio = current_user.bio
     firstName = current_user.firstName
     lastName = current_user.lastName
     name = firstName + ' ' + lastName

     activeUsers =  ActiveUsers.query.all()

     address = current_user.address
     birthday = current_user.birthday

     followersId = [follower for follower in Followers.query.filter_by(owner_id = current_user_id).order_by(desc(Followers.id)).all()]
     followingsId = [following for following in Following.query.filter_by(owner_id = current_user_id).order_by(desc(Following.id)).all()]

     followersCount = len(followersId)
     followingCount = len(followingsId)
     postCount = len(posts)

     user_comrades = Comrades.query.filter_by(owner_id = current_user_id).all()
     comrades = [comrade for comrade in user_comrades]

     return render_template('profile_page.html', 
                              name = name,
                              address = address,
                              birthday = birthday,
                              posts = posts,
                              bio = bio,
                              liked_posts = liked_posts,
                              followersId = followersId,
                              followingsId = followingsId,
                              notifications = notifications,
                              notificationCount = notificationCount,
                              followingCount = followingCount,
                              followersCount = followersCount,
                              postCount = postCount,
                              searchHistory = searchHistory,
                              activeUsers = activeUsers,
                              comrades = comrades)

@views.route('/view-other-profile/<int:id>', methods = ['POST','GET'])
@login_required
def viewOtherProfile(id):

     user_comrades = Comrades.query.filter_by(owner_id = current_user.id).all()
     comrades = [comrade for comrade in user_comrades]

     activeUsers =  ActiveUsers.query.all()
     searchHistory = SearchHistory.query.filter_by(owner_id = current_user.id).order_by(desc(SearchHistory.id)).all()
     current_user_id = current_user.id
     userToView = User.query.get_or_404(id)
     posts = Posts.query.filter_by(user_id = id).order_by(desc(Posts.id)).all()
     liked_posts = [like.post_id for like in UserLikedPosts.query.filter_by(user_id = current_user_id).all()]

     do_i_follow_this_user = Following.query.filter_by(owner_id = current_user_id, user_id = id).first()

     respone = False

     notifications = Notifications.query.filter_by(target_id = current_user_id).order_by(desc(Notifications.id)).all()     
     notificationCount = Notifications.query.filter_by(owner_id = current_user_id).first()
     notificationCount = notificationCount.unread_notification_count
     

     if do_i_follow_this_user:
          response = True
     else:
          response = False

     followers = [follower.follower_name for follower in Followers.query.filter_by(owner_id = id).all()]
     followings = [following.following_name for following in Following.query.filter_by(owner_id = id).all()]

     followersCount = len(followers)
     followingCount = len(followings)
     postCount = len(posts)


     return render_template('other_user_page.html',
                              user = userToView,
                              posts = posts,
                              liked_posts = liked_posts,
                              do_i_follow_this = response,
                              followers = followers,
                              followings = followings,
                              followingCount = followingCount,
                              notifications = notifications,
                              notificationCount = notificationCount,
                              followersCount = followersCount,
                              postCount = postCount,
                              searchHistory = searchHistory,
                              activeUsers = activeUsers,
                              comrades = comrades)







@views.route('/upload-profile', methods =['POST'])
def uploadProfilePicture():
     picture = request.files['profile-pic']

     if not picture:
          flash('No image selected', category="error")
          return redirect('/userprofile')
     
     filename = secure_filename(picture.filename)
     mimetype = picture.mimetype

     profilePic = profilePicture(img = picture.read(), mimetype = mimetype, name = filename, user_id = current_user.id)

     db.session.query(profilePicture).filter_by(user_id = current_user.id).delete()

     db.session.add(profilePic)
     db.session.commit()


     return redirect('/userprofile')

@views.route('/profile-picture/<int:user_id>')
def get_profile_picture(user_id):

     profile_pic = db.session.query(profilePicture).filter_by(user_id = user_id).first()

     if not profile_pic:
          return redirect('/static/defaultImages/default.jpg')

     return send_file(
          io.BytesIO(profile_pic.img),
          mimetype= profile_pic.mimetype,
          as_attachment = False,
          download_name = profile_pic.name
     )

@views.route('/upload-cover', methods = ['POST'])
def uploadCoverPicture():
     coverPictureUploaded = request.files['cover-pic']

     if not coverPictureUploaded:
          flash('No image selected', category="error")
          return redirect('/userprofile')
     
     filename = secure_filename(coverPictureUploaded.filename)
     mimetype = coverPictureUploaded.mimetype

     coverPic = coverPicture(img = coverPictureUploaded.read(), mimetype = mimetype, name = filename, user_id = current_user.id)

     db.session.query(coverPicture).filter_by(user_id = current_user.id).delete()

     db.session.add(coverPic)
     db.session.commit()

     return redirect('/userprofile')

@views.route('/cover-picture/<int:user_id>')
def get_cover_picture(user_id):

     cover_pic = db.session.query(coverPicture).filter_by(user_id = user_id).first()

     if not cover_pic:
          return redirect('/static/defaultImages/defaultPhoto.jpg')

     return send_file(
          io.BytesIO(cover_pic.img),
          mimetype= cover_pic.mimetype,
          as_attachment = False,
          download_name = cover_pic.name

momento/templates/game.html
{%extends 'homepage.html'%}

{%block head%}


<script defer src="{{url_for('static', filename='javascript/game.js')}}"></script>
{% block css %}<link rel="stylesheet" href="{{url_for('static', filename='stylingShit/game.css')}}"> {% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.8.1/socket.io.js" integrity="sha512-8BHxHDLsOHx+flIrQ0DrZcea7MkHqRU5GbTHmbdzMRnAaoCIkZ97PqZcXJkKZckMMhqfoeaJE+DNUVuyoQsO3Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

{%endblock%}

{%block header%}
<li>
     <a class="menu-btn-text" href="/homepage"><i class="fa-solid fa-house"></i></a>
</li>
{%endblock%}


{%block content%}

<div class="container">
     <div id="score"></div>
     <canvas id="game" width="375" height="375"></canvas>
     <div id="introduction">Hold down the mouse to stretch out a stick</div>
     <div id="perfect">DOUBLE SCORE</div>
     <button id="restart">RESTART</button>
   </div>

   <script>
     const CURRENT_USER_ID = "{{ current_user.id }}";
</script>
<script defer src="{{url_for('static', filename = 'javascript/game_socket.js')}}"></script>
{%endblock%}

momento/templates/other_user_page.html
{% extends "profile_page.html"%}


{% block head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.8.1/socket.io.js" integrity="sha512-8BHxHDLsOHx+flIrQ0DrZcea7MkHqRU5GbTHmbdzMRnAaoCIkZ97PqZcXJkKZckMMhqfoeaJE+DNUVuyoQsO3Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<link rel="stylesheet" href="{{url_for('static', filename = 'stylingShit/other_user_page.css')}}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% block title %}
     {{user.firstName + " " + user.lastName}}
{% endblock %}
{% endblock %}



{% block content %}
{% block header%}

<li>
     <a class="menu-btn-text" href="/homepage"><i class="fa-solid fa-house"></i></a>
</li>


{% endblock %}
<div class="left-side">
     <div class="cover-profile-container">
          <div class="cover-container">
               <img src="{{url_for('views.get_cover_picture', user_id = user.id)}}" alt="">
          </div>
          <div class="profile-container">
               <img src="{{url_for('views.get_profile_picture', user_id = user.id)}}" alt="">

               <div>
                    <div class="head">
                         <h2>{{user.firstName + " " + user.lastName}}</h2>
                    {% if do_i_follow_this%}
                  
                    <button id="follow-{{user.id}}" class="unfollow-btn" onclick="followToggle('{{user.id}}', '{{current_user.id}}')">Unfollow</button>
             
                    
                    {%else%}
                   
                    <button id="follow-{{user.id}}" class="follow-btn" onclick="followToggle('{{user.id}}', '{{current_user.id}}')">Follow</button>
                
                    
                    {%endif%}

                    </div>
                    
                    <ul class="count-container-tablet">
                         <div>
                              <h2>{{postCount}}</h2>
                              <h3>Posts</h3>
                         </div>
                         <div>
                              <h2>{{followersCount}}</h2>
                              <h3>Followers</h3>
                         </div>
                         <div>
                              <h2>{{followingCount}}</h2>
                              <h3>Following</h3>
                         </div>
                    </ul>
               </div>
               
          </div>
          
     </div>
     <div class="info-container">
          <ul>
               <li class="bio">"{{user.bio}}"</li>
               <li>{{user.address}}</li>
               <li>{{user.birthday}}</li>
          </ul>
     </div>
</div>

<div class="right-side">
     <div class="timeline">
          {% for post in posts%}
          <div class="post-item">

               <div class="post-header">
                    <div class="profile-name">
                         <img src="{{url_for('views.get_profile_picture', user_id = post.user_id)}}" alt="">
                         <h3>{{user.firstName + " " + user.lastName}}</h3>
                    </div>
                    <h4>{{post.datePost}}</h4>
               </div>
               <div class="post-content">
                    <p class="caption">{{post.caption}}</p>
                    {%if 'image' in post.mimetype%}
                         <img src="{{url_for('views.get_post_picture', user_id = post.id)}}" alt="User Picture">
                    {%elif 'video' in post.mimetype%}
                         <video controls src="{{url_for('views.get_post_picture', user_id = post.id)}}" type="{{post.mimetype }}"></video>
                    {%endif%}
               </div>
               <div class="post-action">
                    <button id="like-btn-{{post.id}}" class="like-btn {% if post.id in liked_posts %}liked{% endif %}" onclick="toggleLike('{{post.id}}','{{current_user.id}}')">
                         {% if post.id in liked_posts %}
                              <i class="fa-solid fa-heart"></i>
                         {%else%}
                              <i class="fa-regular fa-heart"></i>
                         {% endif %}
                    </button>
                    <p id="like-count-{{post.id}}" class="like-count" onmouseenter="viewLikes('{{post.id}}')">{{post.like_count}}</p>
                    <div class="user-who-likes userWhoLikes" id="user-who-likes-{{post.id}}"></div>

                    <div class="form">
                         <input type="text" placeholder="Comment" name ="comment" required="" id="comment-text-{{post.id}}">
                         <button type="submit" onclick="sendComment('{{post.id}}')"><i class="fa-solid fa-paper-plane"></i></button>
                    </div>

                    <button type="button" onclick="viewComment('{{post.id}}')" class="comment-btn" id="comment-section-btn-{{post.id}}"><i class="fa-regular fa-comment"></i></button>
                    <span id="comment-section-counter-{{post.id}}">{{post.comment_count}}</span>
                    <div class="comment-box-popup">
                         <div class="comment-box">
                              <div class="post-info">
                                   <p>{{post.nameWhoPost}}'s post</p>
                              </div>
     
                              <button class="close-comment-box"><i class="fa-solid fa-circle-xmark"></i></button>
                              
                              <ul class="comment-list-container">
                                   <!-- <li class="comment-list">
                                   
                                        <div>
                                             <img src="{{url_for('static', filename = 'defaultImages/default.jpg')}}" alt="">
                                             <p class="name">Marc Rainier Reyes:</p>
                                        </div>
                                        <p class="comment-content">jccjwnw</p>
                                        <p class="date">01/24/0000</p>
                                        
                                   </li> -->
                              </ul>
                              
                             
                              
                         </div>
                    </div>
               </div>
               
          </div>
          {%endfor%}
     </div>
</div>
<script>
     const CURRENT_USER_ID = "{{ current_user.id }}";
</script>
<script src="{{url_for('static', filename = 'javascript/otheruserpage.js')}}">
    
</script>



{% endblock %}

momento/templates/profile_page.html
{% extends "base.html"%}
{% block css %}<link rel="stylesheet" href="{{url_for('static', filename='stylingShit/userprofile.css')}}"> {% endblock %}
{% block title%} Profile Page {% endblock %}

{% block content %}

{% block header%}
{%block icon%}<link rel="icon" type="image/x-icon" href="{{url_for('static', filename = 'icons/iconNamin.png')}}">{%endblock%}
<li>
     <a class="menu-btn-text" href="/homepage"><i class="fa-solid fa-house"></i></a>
</li>


{% endblock %}

<div class="edit-cover-picture-popup hidden">
     <div class="edit-cover-picture-container">
          <h1>Edit your Cover Picture</h1>
          <button class="exit-edit-cover">x</button>
          
          <form action="/upload-cover" method="post" enctype="multipart/form-data">
               <input type="file" placeholder="Upload Cover Picture" name="cover-pic">
               <input type="submit" value="Upload">
          </form>

     </div>
</div>
<div class="edit-profile-picture-popup hidden">
     <div class="edit-profile-picture-container">
          <h1>Edit your Profile Picture</h1>
          <button class="exit-edit">x</button>

          <form action="/upload-profile" method="post" enctype="multipart/form-data">
               <input type="file" placeholder="Upload Profile Picture" name="profile-pic">
               <input type="submit" value="Upload">
          </form>

     </div>
</div>
     <div class="cover-profile-container">

          <div class="cover-container">
               <img src="{{url_for('views.get_cover_picture', user_id = current_user.id)}}" alt="">
               <button id="edit-cover-picture"><i class="fa-solid fa-pencil"></i></button>
          </div>
         

          <div class="profile-container">

               <div class="head">
                    <img src="{{url_for('views.get_profile_picture', user_id = current_user.id)}}" alt="">
                    <button id="edit-profile-picture"><i class="fa-solid fa-pencil"></i></button>
               </div>
               
              

               <div class="body">
                    <h1 class="namee">{{name}}</h1>

                    <ul class="count-container-tablet">
                         <div>
                              <h2>{{postCount}}</h2>
                              <h3>Posts</h3>
                         </div>
                         <div>
                              <h2>{{followersCount}}</h2>
                              <h3>Followers</h3>
                         </div>
                         <div>
                              <h2>{{followingCount}}</h2>
                              <h3>Following</h3>
                         </div>
                    </ul>

               </div>
               

          </div>

     </div>

                         {% with messages = get_flashed_messages(with_categories = true)%}
                         {% if messages %}
                              {% for category, msg in messages %}
                                   {% if category == 'error' %}
                                   <div class="prompt-container">
                                        <div class="error-msg">
                                             <h2>{{msg}}</h2>
                                             <button class="exit-prompt">x</button>
                                        </div> 
                                   </div>
                                   {% endif %}
                              {% endfor %}
                         {% endif %}
                         {% endwith %}

     <div class="info-container">
          
          <ul class="count-container">
               <div>
                    <h2>{{postCount}}</h2>
                    <h3>Posts</h3>
               </div>
               <div>
                    <h2>{{followersCount}}</h2>
                    <h3>Followers</h3>
               </div>
               <div>
                    <h2>{{followingCount}}</h2>
                    <h3>Following</h3>
               </div>
          </ul>
          <ul>
               <li class="bio">"{{bio}}"</li>
               <li>{{address}}</li>
               <li>{{birthday}}</li>
          </ul>
     </div>
     
     <div class="timeline">
          <div class="post-follower-container">
               <button style="border: 2px solid black" id="postsToggleBtn">Posts</button>
               <button id="followersToggleBtn">Followers</button>
               <button id="followingToggleBtn">Following</button>
          </div>
          <div class="post-container">

               {% for post in posts %}
               <div class="post-item">

                    <div class="post-header">
                         <div class="profile-name">
                              <img src="{{url_for('views.get_profile_picture', user_id = post.user_id)}}" alt="">
                              <h3>{{name}}</h3>
                         </div>
                         <h5>{{post.datePost}}</h5>
                    </div>
                    <div class="post-content">
                         <p class="caption">{{post.caption}}</p>
                         {%if 'image' in post.mimetype%}
                              <img src="{{url_for('views.get_post_picture', user_id = post.id)}}" alt="User Picture">
                         {%elif 'video' in post.mimetype%}
                              <video controls src="{{url_for('views.get_post_picture', user_id = post.id)}}" type="{{post.mimetype }}"></video>
                         {%endif%}
                    </div>

                    <div class="post-action">
                         <button id="like-btn-{{post.id}}" class="like-btn {% if post.id in liked_posts %}liked{% endif %}" onclick="toggleLike('{{post.id}}','{{current_user.id}}')">
                              {% if post.id in liked_posts %}
                                   <i class="fa-solid fa-heart"></i>
                              {%else%}
                                   <i class="fa-regular fa-heart"></i>
                              {% endif %}
                         </button>
                         <p id="like-count-{{post.id}}" class="like-count" onmouseenter="viewLikes('{{post.id}}')">{{post.like_count}}</p>

                         <div class="user-who-likes userWhoLikes" id="user-who-likes-{{post.id}}">
                         
                         </div>
     
                         <div class="form">
                              <input type="text" placeholder="Comment" name ="comment" required="" id="comment-text-{{post.id}}">
                              <button type="submit" onclick="sendComment('{{post.id}}')"><i class="fa-solid fa-paper-plane"></i></button>
                         </div>

                         <button type="button" onclick="viewComment('{{post.id}}')" class="comment-btn" id="comment-section-btn-{{post.id}}"><i class="fa-regular fa-comment"></i></button>
                         <span id="comment-section-counter-{{post.id}}">{{post.comment_count}}</span>

                         <a class="delete-btn" href="/delete-post/{{post.id}}"><i class="fa-solid fa-trash-can"></i></a>

                         <div class="comment-box-popup">
                              <div class="comment-box">
                                   <div class="post-info">
                                        <p>{{post.nameWhoPost}}'s post</p>
                                   </div>
          
                                   <button class="close-comment-box"><i class="fa-solid fa-circle-xmark"></i></button>
                                   
                                   <ul class="comment-list-container">
                                        <!-- <li class="comment-list">
                                        
                                             <div>
                                                  <img src="{{url_for('static', filename = 'defaultImages/default.jpg')}}" alt="">
                                                  <p class="name">Marc Rainier Reyes:</p>
                                             </div>
                                             <p class="comment-content">jccjwnw</p>
                                             <p class="date">01/24/0000</p>
                                             
                                        </li> -->
                                   </ul>
                                   
                                  
                                   
                              </div>
                         </div>

                    </div>
                    
               </div>
               {% endfor %}

          </div>
          <div class="following-container hidden">
               {% for following in followingsId%}

                    <a href="/view-other-profile/{{following.user_id}}">
                         <img src="{{url_for('views.get_profile_picture', user_id = following.user_id)}}" alt="{{following}} Photo">
                         
                         <h4>{{following.following_name}}</h4>
                    </a>
                        
                         
                    
                    
               {%endfor%}
               
               
          </div>
          <div class="followers-container hidden">
               {% for follower in followersId%}

                    <a href="/view-other-profile/{{follower.user_id}}">
                         <img src="{{url_for('views.get_profile_picture', user_id = follower.user_id)}}" alt="{{following}} Photo">
                         <h4>{{follower.follower_name}}</h4>
                    </a>
                         
                    
                    
               {%endfor%}
               
          </div>
     </div>

     <script>
          const CURRENT_USER_ID = "{{ current_user.id }}";
     </script>
<script src="{{url_for('static', filename = 'javascript/userprofile.js')}}"></script>
{% endblock %}